# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT config.wsgi.deploy

beta_settings:
    cloud_sql_instances: "delicious-apiserver:asia-northeast1:delicious-sql"

runtime_config:
  python_version: 3
# [END runtime]
